# Combine all price, generation and load data into one dataframe

In [116]:
import pandas as pd

In [117]:
weather = pd.read_csv('./data/weather.csv')

In [118]:
import os

In [119]:
generation_first = pd.read_csv('./data/Actual Generation per Production Type_201501010000-201601010000.csv')

In [120]:
price_first = pd.read_csv('./data/Day-ahead Prices_201501010000-201601010000.csv')

In [121]:
load_first = pd.read_csv('./data/Total Load - Day Ahead _ Actual_201501010000-201601010000.csv')

In [77]:
generation = pd.DataFrame(columns = generation_first.columns)

In [78]:
price = pd.DataFrame(columns = price_first.columns)

In [79]:
load = pd.DataFrame(columns = load_first.columns)

In [80]:
import glob

In [81]:
generation_files = glob.glob('./data/Actual*')

In [82]:
generation_files.sort()

In [83]:
price_files = glob.glob('./data/Day*')
price_files.sort()

In [84]:
load_files = glob.glob('./data/Total*')
load_files.sort()

In [102]:
for file in generation_files:
    df = pd.read_csv(file)
    generation = pd.concat([generation, df], axis=0)
    #generation.merge(df, how='outer')

In [105]:
generation

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Brown coal/Lignite - Actual Aggregated [MW],Fossil Coal-derived gas - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Oil shale - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],...,Hydro Run-of-river and poundage - Actual Aggregated [MW],Hydro Water Reservoir - Actual Aggregated [MW],Marine - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],Other renewable - Actual Aggregated [MW],Solar - Actual Aggregated [MW],Waste - Actual Aggregated [MW],Wind Offshore - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW]
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00 (CET/CEST),865.0,n/e,n/e,861.0,655.0,1.0,n/e,396.0,...,735.0,n/e,n/e,2774.0,208.0,44.0,n/e,55.0,n/e,214.0
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00 (CET/CEST),874.0,n/e,n/e,858.0,646.0,1.0,n/e,397.0,...,668.0,n/e,n/e,2773.0,208.0,44.0,n/e,49.0,n/e,208.0
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00 (CET/CEST),880.0,n/e,n/e,843.0,648.0,1.0,n/e,396.0,...,669.0,n/e,n/e,2773.0,208.0,44.0,n/e,47.0,n/e,250.0
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00 (CET/CEST),872.0,n/e,n/e,733.0,646.0,1.0,n/e,396.0,...,605.0,n/e,n/e,2773.0,208.0,44.0,n/e,47.0,n/e,264.0
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00 (CET/CEST),881.0,n/e,n/e,734.0,646.0,1.0,n/e,399.0,...,594.0,n/e,n/e,2773.0,208.0,44.0,n/e,45.0,n/e,274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,BZN|FI,31.12.2022 19:00 - 31.12.2022 20:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8757,BZN|FI,31.12.2022 20:00 - 31.12.2022 21:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8758,BZN|FI,31.12.2022 21:00 - 31.12.2022 22:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8759,BZN|FI,31.12.2022 22:00 - 31.12.2022 23:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8760,BZN|FI,31.12.2022 23:00 - 01.01.2023 00:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-

In [106]:
for file in price_files:
    df = pd.read_csv(file)
    price = pd.concat([price, df], axis=0)
    #generation.merge(df, how='outer')

In [107]:
for file in load_files:
    df = pd.read_csv(file)
    load = pd.concat([load, df], axis=0)
    #generation.merge(df, how='outer')

In [108]:
price

,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,BZN|FI
0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,NaN
1,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,NaN
2,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,NaN
3,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,NaN
4,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,NaN
...,...,...,...,...
8756,31.12.2022 19:00 - 31.12.2022 20:00,-,NaN,NaN
8757,31.12.2022 20:00 - 31.12.2022 21:00,-,NaN,NaN
8758,31.12.2022 21:00 - 31.12.2022 22:00,-,NaN,NaN
8759,31.12.2022 22:00 - 31.12.2022 23:00,-,NaN,NaN
8760,31.12.2022 23:00 - 01.01.2023 00:00,-,NaN,NaN

In [109]:
load

,Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|ES,Actual Total Load [MW] - BZN|ES
0,01.01.2015 00:00 - 01.01.2015 01:00,26118.0,25385.0
1,01.01.2015 01:00 - 01.01.2015 02:00,24934.0,24382.0
2,01.01.2015 02:00 - 01.01.2015 03:00,23515.0,22734.0
3,01.01.2015 03:00 - 01.01.2015 04:00,22642.0,21286.0
4,01.01.2015 04:00 - 01.01.2015 05:00,21785.0,20264.0
...,...,...,...
24809,31.12.2022 22:45 - 31.12.2022 23:00,-,-
24810,31.12.2022 23:00 - 31.12.2022 23:15,-,-
24811,31.12.2022 23:15 - 31.12.2022 23:30,-,-
24812,31.12.2022 23:30 - 31.12.2022 23:45,-,-
24813,31.12.2022 23:45 - 01.01.2023 00:00,-,-

In [112]:
price.to_csv('./data/all_pricedata.csv')

In [113]:
load.to_csv('./data/all_load_data.csv')

In [114]:
generation.to_csv('./data/all_generation_data.csv')