# Combine all price, generation and load data into one dataframe

In [1]:
import pandas as pd

In [2]:
weather = pd.read_csv('./data/weather.csv')

In [3]:
import os

In [4]:
generation_first = pd.read_csv('./data/Actual Generation per Production Type_201501010000-201601010000.csv')

In [5]:
price_first = pd.read_csv('./data/Day-ahead Prices_201501010000-201601010000.csv')

In [6]:
load_first = pd.read_csv('./data/Total Load - Day Ahead _ Actual_201501010000-201601010000.csv')

In [7]:
generation = pd.DataFrame(columns = generation_first.columns)

In [8]:
price = pd.DataFrame(columns = price_first.columns)

In [9]:
load = pd.DataFrame(columns = load_first.columns)

In [10]:
import glob

In [11]:
generation_files = glob.glob('./data/Actual*')

In [12]:
generation_files.sort()

In [13]:
price_files = glob.glob('./data/Day*')
price_files.sort()

In [14]:
price_files

['./data/Day-ahead Prices_201501010000-201601010000.csv',
 './data/Day-ahead Prices_201601010000-201701010000.csv',
 './data/Day-ahead Prices_201701010000-201801010000.csv',
 './data/Day-ahead Prices_201801010000-201901010000.csv',
 './data/Day-ahead Prices_201901010000-202001010000.csv',
 './data/Day-ahead Prices_202001010000-202101010000.csv',
 './data/Day-ahead Prices_202101010000-202201010000.csv',
 './data/Day-ahead Prices_202201010000-202301010000.csv']

In [15]:
load_files = glob.glob('./data/Total*')
load_files.sort()

In [16]:
for file in generation_files:
    df = pd.read_csv(file)
    generation = pd.concat([generation, df], axis=0)
    #generation.merge(df, how='outer')

In [17]:
generation

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Brown coal/Lignite - Actual Aggregated [MW],Fossil Coal-derived gas - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Oil shale - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],...,Hydro Run-of-river and poundage - Actual Aggregated [MW],Hydro Water Reservoir - Actual Aggregated [MW],Marine - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],Other renewable - Actual Aggregated [MW],Solar - Actual Aggregated [MW],Waste - Actual Aggregated [MW],Wind Offshore - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW]
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00 (CET/CEST),865.0,n/e,n/e,861.0,655.0,1.0,n/e,396.0,...,735.0,n/e,n/e,2774.0,208.0,44.0,n/e,55.0,n/e,214.0
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00 (CET/CEST),874.0,n/e,n/e,858.0,646.0,1.0,n/e,397.0,...,668.0,n/e,n/e,2773.0,208.0,44.0,n/e,49.0,n/e,208.0
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00 (CET/CEST),880.0,n/e,n/e,843.0,648.0,1.0,n/e,396.0,...,669.0,n/e,n/e,2773.0,208.0,44.0,n/e,47.0,n/e,250.0
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00 (CET/CEST),872.0,n/e,n/e,733.0,646.0,1.0,n/e,396.0,...,605.0,n/e,n/e,2773.0,208.0,44.0,n/e,47.0,n/e,264.0
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00 (CET/CEST),881.0,n/e,n/e,734.0,646.0,1.0,n/e,399.0,...,594.0,n/e,n/e,2773.0,208.0,44.0,n/e,45.0,n/e,274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,BZN|FI,31.12.2022 19:00 - 31.12.2022 20:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8757,BZN|FI,31.12.2022 20:00 - 31.12.2022 21:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8758,BZN|FI,31.12.2022 21:00 - 31.12.2022 22:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8759,BZN|FI,31.12.2022 22:00 - 31.12.2022 23:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8760,BZN|FI,31.12.2022 23:00 - 01.01.2023 00:00 (CET/CEST),-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-

In [18]:
for file in price_files:
    df = pd.read_csv(file)
    price = pd.concat([price, df], axis=0)
    #generation.merge(df, how='outer')

In [19]:
for file in load_files:
    df = pd.read_csv(file)
    load = pd.concat([load, df], axis=0)
    #generation.merge(df, how='outer')

In [20]:
price

,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,BZN|FI
0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,NaN
1,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,NaN
2,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,NaN
3,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,NaN
4,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,NaN
...,...,...,...,...
8756,31.12.2022 19:00 - 31.12.2022 20:00,-,NaN,NaN
8757,31.12.2022 20:00 - 31.12.2022 21:00,-,NaN,NaN
8758,31.12.2022 21:00 - 31.12.2022 22:00,-,NaN,NaN
8759,31.12.2022 22:00 - 31.12.2022 23:00,-,NaN,NaN
8760,31.12.2022 23:00 - 01.01.2023 00:00,-,NaN,NaN

In [21]:
load

,Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI
0,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0
1,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0
2,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0
3,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0
4,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0
...,...,...,...
8756,31.12.2022 19:00 - 31.12.2022 20:00,-,-
8757,31.12.2022 20:00 - 31.12.2022 21:00,-,-
8758,31.12.2022 21:00 - 31.12.2022 22:00,-,-
8759,31.12.2022 22:00 - 31.12.2022 23:00,-,-
8760,31.12.2022 23:00 - 01.01.2023 00:00,-,-

In [22]:
price.to_csv('./data/all_pricedata.csv')

In [23]:
load.to_csv('./data/all_load_data.csv')

In [24]:
generation.to_csv('./data/all_generation_data.csv')

# Merge into one dataframe

In [25]:
generation.dtypes

Area                                                         object
MTU                                                          object
Biomass  - Actual Aggregated [MW]                            object
Fossil Brown coal/Lignite  - Actual Aggregated [MW]          object
Fossil Coal-derived gas  - Actual Aggregated [MW]            object
Fossil Gas  - Actual Aggregated [MW]                         object
Fossil Hard coal  - Actual Aggregated [MW]                   object
Fossil Oil  - Actual Aggregated [MW]                         object
Fossil Oil shale  - Actual Aggregated [MW]                   object
Fossil Peat  - Actual Aggregated [MW]                        object
Geothermal  - Actual Aggregated [MW]                         object
Hydro Pumped Storage  - Actual Aggregated [MW]               object
Hydro Pumped Storage  - Actual Consumption [MW]              object
Hydro Run-of-river and poundage  - Actual Aggregated [MW]    object
Hydro Water Reservoir  - Actual Aggregated [MW]              object
Marine  - Actual Aggregated [MW]                             object
Nuclear  - Actual Aggregated [MW]                            object
Other  - Actual Aggregated [MW]                              object
Other renewable  - Actual Aggregated [MW]                    object
Solar  - Actual Aggregated [MW]                              object
Waste  - Actual Aggregated [MW]                              object
Wind Offshore  - Actual Aggregated [MW]                      object
Wind Onshore  - Actual Aggregated [MW]                       object
dtype: object

In [26]:
generation.MTU.str.replace('[(CET/CEST)].*','',  regex = True).str.strip()

0       01.01.2015 00:00 - 01.01.2015 01:00
1       01.01.2015 01:00 - 01.01.2015 02:00
2       01.01.2015 02:00 - 01.01.2015 03:00
3       01.01.2015 03:00 - 01.01.2015 04:00
4       01.01.2015 04:00 - 01.01.2015 05:00
                       ...
8756    31.12.2022 19:00 - 31.12.2022 20:00
8757    31.12.2022 20:00 - 31.12.2022 21:00
8758    31.12.2022 21:00 - 31.12.2022 22:00
8759    31.12.2022 22:00 - 31.12.2022 23:00
8760    31.12.2022 23:00 - 01.01.2023 00:00
Name: MTU, Length: 70136, dtype: object

In [27]:
generation['MTU'] = generation.MTU.str.replace('[(CET/CEST)].*','',  regex = True).str.strip()

In [28]:
generation

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Brown coal/Lignite - Actual Aggregated [MW],Fossil Coal-derived gas - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Oil shale - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],...,Hydro Run-of-river and poundage - Actual Aggregated [MW],Hydro Water Reservoir - Actual Aggregated [MW],Marine - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],Other renewable - Actual Aggregated [MW],Solar - Actual Aggregated [MW],Waste - Actual Aggregated [MW],Wind Offshore - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW]
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,n/e,n/e,861.0,655.0,1.0,n/e,396.0,...,735.0,n/e,n/e,2774.0,208.0,44.0,n/e,55.0,n/e,214.0
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,n/e,n/e,858.0,646.0,1.0,n/e,397.0,...,668.0,n/e,n/e,2773.0,208.0,44.0,n/e,49.0,n/e,208.0
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,n/e,n/e,843.0,648.0,1.0,n/e,396.0,...,669.0,n/e,n/e,2773.0,208.0,44.0,n/e,47.0,n/e,250.0
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,n/e,n/e,733.0,646.0,1.0,n/e,396.0,...,605.0,n/e,n/e,2773.0,208.0,44.0,n/e,47.0,n/e,264.0
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,n/e,n/e,734.0,646.0,1.0,n/e,399.0,...,594.0,n/e,n/e,2773.0,208.0,44.0,n/e,45.0,n/e,274.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,BZN|FI,31.12.2022 19:00 - 31.12.2022 20:00,-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8757,BZN|FI,31.12.2022 20:00 - 31.12.2022 21:00,-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8758,BZN|FI,31.12.2022 21:00 - 31.12.2022 22:00,-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8759,BZN|FI,31.12.2022 22:00 - 31.12.2022 23:00,-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-
8760,BZN|FI,31.12.2022 23:00 - 01.01.2023 00:00,-,n/e,n/e,-,-,-,n/e,-,...,-,n/e,n/e,-,-,-,n/e,-,n/e,-

In [29]:
generation.iloc[0, 1] == load.iloc[0, 0]

True

In [30]:
generation.iloc[0, 1]

'01.01.2015 00:00 - 01.01.2015 01:00'

In [31]:
load.iloc[0, 0]

'01.01.2015 00:00 - 01.01.2015 01:00'

The timestamps seem to be in the same format so I can just merge them based on the time.

In [32]:
generation.iloc[0, 1] == price.iloc[0, 0]

True

In [33]:
df = generation.merge(load, how='outer', left_on = 'MTU', right_on = 'Time (CET/CEST)')

In [34]:
df = df.merge(price, how='outer', left_on = 'MTU', right_on = 'MTU (CET/CEST)')

In [35]:
df.head()

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Brown coal/Lignite - Actual Aggregated [MW],Fossil Coal-derived gas - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Oil shale - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],...,Waste - Actual Aggregated [MW],Wind Offshore - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW],Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,BZN|FI
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,n/e,n/e,861.0,655.0,1.0,n/e,396.0,...,55.0,n/e,214.0,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,NaN
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,n/e,n/e,858.0,646.0,1.0,n/e,397.0,...,49.0,n/e,208.0,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,NaN
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,n/e,n/e,843.0,648.0,1.0,n/e,396.0,...,47.0,n/e,250.0,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,NaN
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,n/e,n/e,733.0,646.0,1.0,n/e,396.0,...,47.0,n/e,264.0,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,NaN
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,n/e,n/e,734.0,646.0,1.0,n/e,399.0,...,45.0,n/e,274.0,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,NaN

In [36]:
len(df[df['BZN|FI'].isna() == False])

0

There is no valid information in BZN|FI

In [37]:
len(generation.index)

70136

In [38]:
len(df.index)

70184

In [39]:
len(price.index)

70136

In [40]:
len(load.index)

70136

There seem to be some dates for which there is missing information in prices and also some days for which there is more info in prices or loads than in generation.

In [41]:
df.iloc[0, 4] == 'n/e'

True

Let's replace all n/e values with np.nan

In [42]:
import numpy as np

In [43]:
for column in df.columns:
    df.loc[df[column] == 'n/e', column] = np.nan
    df.loc[df[column] == '-', column] = np.nan

In [44]:
df

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Brown coal/Lignite - Actual Aggregated [MW],Fossil Coal-derived gas - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Oil shale - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],...,Waste - Actual Aggregated [MW],Wind Offshore - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW],Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,BZN|FI
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,NaN,NaN,861.0,655.0,1.0,NaN,396.0,...,55.0,NaN,214.0,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,NaN
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,NaN,NaN,858.0,646.0,1.0,NaN,397.0,...,49.0,NaN,208.0,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,NaN
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,NaN,NaN,843.0,648.0,1.0,NaN,396.0,...,47.0,NaN,250.0,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,NaN
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,NaN,NaN,733.0,646.0,1.0,NaN,396.0,...,47.0,NaN,264.0,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,NaN
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,NaN,NaN,734.0,646.0,1.0,NaN,399.0,...,45.0,NaN,274.0,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70179,BZN|FI,31.12.2022 19:00 - 31.12.2022 20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,31.12.2022 19:00 - 31.12.2022 20:00,NaN,NaN,31.12.2022 19:00 - 31.12.2022 20:00,NaN,NaN,NaN
70180,BZN|FI,31.12.2022 20:00 - 31.12.2022 21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,31.12.2022 20:00 - 31.12.2022 21:00,NaN,NaN,31.12.2022 20:00 - 31.12.2022 21:00,NaN,NaN,NaN
70181,BZN|FI,31.12.2022 21:00 - 31.12.2022 22:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,31.12.2022 21:00 - 31.12.2022 22:00,NaN,NaN,31.12.2022 21:00 - 31.12.2022 22:00,NaN,NaN,NaN
70182,BZN|FI,31.12.2022 22:00 - 31.12.2022 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,31.12.2022 22:00 - 31.12.2022 23:00,NaN,NaN,31.12.2022 22:00 - 31.12.2022 23:00,NaN,NaN,NaN
70183,BZN|FI,31.12.2022 23:00 - 01.01.2023 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,31.12.2022 23:00 - 01.01.2023 00:00,NaN,NaN,31.12.2022 23:00 - 01.01.2023 00:00,NaN,NaN,NaN

Calculate the number of missing values in each column:

In [45]:
for column in df.columns:
    print('number of missing values in column', column)
    print(df[column].isna().sum())

number of missing values in column Area
0
number of missing values in column MTU
0
number of missing values in column Biomass  - Actual Aggregated [MW]
2395
number of missing values in column Fossil Brown coal/Lignite  - Actual Aggregated [MW]
70184
number of missing values in column Fossil Coal-derived gas  - Actual Aggregated [MW]
70184
number of missing values in column Fossil Gas  - Actual Aggregated [MW]
2397
number of missing values in column Fossil Hard coal  - Actual Aggregated [MW]
2397
number of missing values in column Fossil Oil  - Actual Aggregated [MW]
2399
number of missing values in column Fossil Oil shale  - Actual Aggregated [MW]
70184
number of missing values in column Fossil Peat  - Actual Aggregated [MW]
2396
number of missing values in column Geothermal  - Actual Aggregated [MW]
70184
number of missing values in column Hydro Pumped Storage  - Actual Aggregated [MW]
70184
number of missing values in column Hydro Pumped Storage  - Actual Consumption [MW]
70184
number of missing values in column Hydro Run-of-river and poundage  - Actual Aggregated [MW]
2397
number of missing values in column Hydro Water Reservoir  - Actual Aggregated [MW]
70184
number of missing values in column Marine  - Actual Aggregated [MW]
70184
number of missing values in column Nuclear  - Actual Aggregated [MW]
2393
number of missing values in column Other  - Actual Aggregated [MW]
2397
number of missing values in column Other renewable  - Actual Aggregated [MW]
2397
number of missing values in column Solar  - Actual Aggregated [MW]
70184
number of missing values in column Waste  - Actual Aggregated [MW]
2395
number of missing values in column Wind Offshore  - Actual Aggregated [MW]
70184
number of missing values in column Wind Onshore  - Actual Aggregated [MW]
2393
number of missing values in column Time (CET/CEST)
0
number of missing values in column Day-ahead Total Load Forecast [MW] - BZN|FI
2344
number of missing values in column Actual Total Load [MW] - BZN|FI
2379
number of missing values in column MTU (CET/CEST)
0
number of missing values in column Day-ahead Price [EUR/MWh]
2343
number of missing values in column Currency
2317
number of missing values in column BZN|FI
70184

There are 8763 values in df for which there is no price data available.

Remove all columns that contain no other data than NaN values:

In [46]:
for column in df.columns:
    if df[column].isna().sum() == len(df.index):
        print('drop column', column)
        df.drop(columns = column, inplace = True)

drop column Fossil Brown coal/Lignite  - Actual Aggregated [MW]
drop column Fossil Coal-derived gas  - Actual Aggregated [MW]
drop column Fossil Oil shale  - Actual Aggregated [MW]
drop column Geothermal  - Actual Aggregated [MW]
drop column Hydro Pumped Storage  - Actual Aggregated [MW]
drop column Hydro Pumped Storage  - Actual Consumption [MW]
drop column Hydro Water Reservoir  - Actual Aggregated [MW]
drop column Marine  - Actual Aggregated [MW]
drop column Solar  - Actual Aggregated [MW]
drop column Wind Offshore  - Actual Aggregated [MW]
drop column BZN|FI

In [47]:
df

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],Hydro Run-of-river and poundage - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],Other renewable - Actual Aggregated [MW],Waste - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW],Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,861.0,655.0,1.0,396.0,735.0,2774.0,208.0,44.0,55.0,214.0,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,858.0,646.0,1.0,397.0,668.0,2773.0,208.0,44.0,49.0,208.0,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,843.0,648.0,1.0,396.0,669.0,2773.0,208.0,44.0,47.0,250.0,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,733.0,646.0,1.0,396.0,605.0,2773.0,208.0,44.0,47.0,264.0,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,734.0,646.0,1.0,399.0,594.0,2773.0,208.0,44.0,45.0,274.0,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70179,BZN|FI,31.12.2022 19:00 - 31.12.2022 20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.12.2022 19:00 - 31.12.2022 20:00,NaN,NaN,31.12.2022 19:00 - 31.12.2022 20:00,NaN,NaN
70180,BZN|FI,31.12.2022 20:00 - 31.12.2022 21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.12.2022 20:00 - 31.12.2022 21:00,NaN,NaN,31.12.2022 20:00 - 31.12.2022 21:00,NaN,NaN
70181,BZN|FI,31.12.2022 21:00 - 31.12.2022 22:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.12.2022 21:00 - 31.12.2022 22:00,NaN,NaN,31.12.2022 21:00 - 31.12.2022 22:00,NaN,NaN
70182,BZN|FI,31.12.2022 22:00 - 31.12.2022 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.12.2022 22:00 - 31.12.2022 23:00,NaN,NaN,31.12.2022 22:00 - 31.12.2022 23:00,NaN,NaN
70183,BZN|FI,31.12.2022 23:00 - 01.01.2023 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.12.2022 23:00 - 01.01.2023 00:00,NaN,NaN,31.12.2022 23:00 - 01.01.2023 00:00,NaN,NaN

Create a timestamp from MTU so that I can drop all rows after the date for which we have no data available.

In [48]:
df['start_time'] = df.MTU.str.split('-', expand = True)[0].str.strip()

In [49]:
df['end_time'] = df.MTU.str.split('-', expand = True)[1].str.strip()

In [50]:
df.head()

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],Hydro Run-of-river and poundage - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],...,Waste - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW],Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,start_time,end_time
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,861.0,655.0,1.0,396.0,735.0,2774.0,208.0,...,55.0,214.0,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,01.01.2015 00:00,01.01.2015 01:00
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,858.0,646.0,1.0,397.0,668.0,2773.0,208.0,...,49.0,208.0,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,01.01.2015 01:00,01.01.2015 02:00
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,843.0,648.0,1.0,396.0,669.0,2773.0,208.0,...,47.0,250.0,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,01.01.2015 02:00,01.01.2015 03:00
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,733.0,646.0,1.0,396.0,605.0,2773.0,208.0,...,47.0,264.0,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,01.01.2015 03:00,01.01.2015 04:00
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,734.0,646.0,1.0,399.0,594.0,2773.0,208.0,...,45.0,274.0,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,01.01.2015 04:00,01.01.2015 05:00

In [51]:
df['start_time'] = pd.to_datetime(df.start_time, format='%d.%m.%Y %H:%M')

In [52]:
df['end_time'] = pd.to_datetime(df.end_time, format='%d.%m.%Y %H:%M')

In [53]:
df.start_time.max()

Timestamp('2022-12-31 23:00:00')

Find the first NaN date

In [54]:
df[df.start_time > pd.Timestamp('2022-09-26T13')].head(50)

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],Hydro Run-of-river and poundage - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],...,Waste - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW],Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,start_time,end_time
67863,BZN|FI,26.09.2022 14:00 - 26.09.2022 15:00,810,142,318,1,222,962,3726,55,...,23,711,26.09.2022 14:00 - 26.09.2022 15:00,8375,8562,26.09.2022 14:00 - 26.09.2022 15:00,283.97,EUR,2022-09-26 14:00:00,2022-09-26 15:00:00
67864,BZN|FI,26.09.2022 15:00 - 26.09.2022 16:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 15:00 - 26.09.2022 16:00,8371,8510,26.09.2022 15:00 - 26.09.2022 16:00,244.54,EUR,2022-09-26 15:00:00,2022-09-26 16:00:00
67865,BZN|FI,26.09.2022 16:00 - 26.09.2022 17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 16:00 - 26.09.2022 17:00,8391,8405,26.09.2022 16:00 - 26.09.2022 17:00,199.37,EUR,2022-09-26 16:00:00,2022-09-26 17:00:00
67866,BZN|FI,26.09.2022 17:00 - 26.09.2022 18:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 17:00 - 26.09.2022 18:00,8395,8417,26.09.2022 17:00 - 26.09.2022 18:00,180.01,EUR,2022-09-26 17:00:00,2022-09-26 18:00:00
67867,BZN|FI,26.09.2022 18:00 - 26.09.2022 19:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 18:00 - 26.09.2022 19:00,8543,8654,26.09.2022 18:00 - 26.09.2022 19:00,187.85,EUR,2022-09-26 18:00:00,2022-09-26 19:00:00
67868,BZN|FI,26.09.2022 19:00 - 26.09.2022 20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 19:00 - 26.09.2022 20:00,8546,8693,26.09.2022 19:00 - 26.09.2022 20:00,188.18,EUR,2022-09-26 19:00:00,2022-09-26 20:00:00
67869,BZN|FI,26.09.2022 20:00 - 26.09.2022 21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 20:00 - 26.09.2022 21:00,8277,8369,26.09.2022 20:00 - 26.09.2022 21:00,163.21,EUR,2022-09-26 20:00:00,2022-09-26 21:00:00
67870,BZN|FI,26.09.2022 21:00 - 26.09.2022 22:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 21:00 - 26.09.2022 22:00,8232,8340,26.09.2022 21:00 - 26.09.2022 22:00,103.81,EUR,2022-09-26 21:00:00,2022-09-26 22:00:00
67871,BZN|FI,26.09.2022 22:00 - 26.09.2022 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 22:00 - 26.09.2022 23:00,8046,8056,26.09.2022 22:00 - 26.09.2022 23:00,110.02,EUR,2022-09-26 22:00:00,2022-09-26 23:00:00
67872,BZN|FI,26.09.2022 23:00 - 27.09.2022 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,26.09.2022 23:00 - 27.09.2022 00:00,7678,7632,26.09.2022 23:00 - 27.09.2022 00:00,18.77,EUR,2022-09-26 23:00:00,2022-09-27 00:00:00
67873,BZN|FI,27.09.2022 00:00 - 27.09.2022 01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 00:00 - 27.09.2022 01:00,7436,7444,27.09.2022 00:00 - 27.09.2022 01:00,NaN,EUR,2022-09-27 00:00:00,2022-09-27 01:00:00
67874,BZN|FI,27.09.2022 01:00 - 27.09.2022 02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 01:00 - 27.09.2022 02:00,7320,7309,27.09.2022 01:00 - 27.09.2022 02:00,NaN,EUR,2022-09-27 01:00:00,2022-09-27 02:00:00
67875,BZN|FI,27.09.2022 02:00 - 27.09.2022 03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 02:00 - 27.09.2022 03:00,7260,7285,27.09.2022 02:00 - 27.09.2022 03:00,NaN,NaN,2022-09-27 02:00:00,2022-09-27 03:00:00
67876,BZN|FI,27.09.2022 03:00 - 27.09.2022 04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 03:00 - 27.09.2022 04:00,7364,7264,27.09.2022 03:00 - 27.09.2022 04:00,NaN,NaN,2022-09-27 03:00:00,2022-09-27 04:00:00
67877,BZN|FI,27.09.2022 04:00 - 27.09.2022 05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 04:00 - 27.09.2022 05:00,7569,7457,27.09.2022 04:00 - 27.09.2022 05:00,NaN,NaN,2022-09-27 04:00:00,2022-09-27 05:00:00
67878,BZN|FI,27.09.2022 05:00 - 27.09.2022 06:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 05:00 - 27.09.2022 06:00,8142,8176,27.09.2022 05:00 - 27.09.2022 06:00,NaN,NaN,2022-09-27 05:00:00,2022-09-27 06:00:00
67879,BZN|FI,27.09.2022 06:00 - 27.09.2022 07:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 06:00 - 27.09.2022 07:00,8397,8393,27.09.2022 06:00 - 27.09.2022 07:00,NaN,NaN,2022-09-27 06:00:00,2022-09-27 07:00:00
67880,BZN|FI,27.09.2022 07:00 - 27.09.2022 08:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 07:00 - 27.09.2022 08:00,8607,8637,27.09.2022 07:00 - 27.09.2022 08:00,NaN,NaN,2022-09-27 07:00:00,2022-09-27 08:00:00
67881,BZN|FI,27.09.2022 08:00 - 27.09.2022 09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 08:00 - 27.09.2022 09:00,8657,8703,27.09.2022 08:00 - 27.09.2022 09:00,NaN,NaN,2022-09-27 08:00:00,2022-09-27 09:00:00
67882,BZN|FI,27.09.2022 09:00 - 27.09.2022 10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 09:00 - 27.09.2022 10:00,8678,8691,27.09.2022 09:00 - 27.09.2022 10:00,NaN,NaN,2022-09-27 09:00:00,2022-09-27 10:00:00
67883,BZN|FI,27.09.2022 10:00 - 27.09.2022 11:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 10:00 - 27.09.2022 11:00,8677,8738,27.09.2022 10:00 - 27.09.2022 11:00,NaN,NaN,2022-09-27 10:00:00,2022-09-27 11:00:00
67884,BZN|FI,27.09.2022 11:00 - 27.09.2022 12:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 11:00 - 27.09.2022 12:00,8649,NaN,27.09.2022 11:00 - 27.09.2022 12:00,NaN,NaN,2022-09-27 11:00:00,2022-09-27 12:00:00
67885,BZN|FI,27.09.2022 12:00 - 27.09.2022 13:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 12:00 - 27.09.2022 13:00,8552,NaN,27.09.2022 12:00 - 27.09.2022 13:00,NaN,NaN,2022-09-27 12:00:00,2022-09-27 13:00:00
67886,BZN|FI,27.09.2022 13:00 - 27.09.2022 14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 13:00 - 27.09.2022 14:00,8526,NaN,27.09.2022 13:00 - 27.09.2022 14:00,NaN,NaN,2022-09-27 13:00:00,2022-09-27 14:00:00
67887,BZN|FI,27.09.2022 14:00 - 27.09.2022 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 14:00 - 27.09.2022 15:00,8468,NaN,27.09.2022 14:00 - 27.09.2022 15:00,NaN,NaN,2022-09-27 14:00:00,2022-09-27 15:00:00
67888,BZN|FI,27.09.2022 15:00 - 27.09.2022 16:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 15:00 - 27.09.2022 16:00,8459,NaN,27.09.2022 15:00 - 27.09.2022 16:00,NaN,NaN,2022-09-27 15:00:00,2022-09-27 16:00:00
67889,BZN|FI,27.09.2022 16:00 - 27.09.2022 17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 16:00 - 27.09.2022 17:00,8440,NaN,27.09.2022 16:00 - 27.09.2022 17:00,NaN,NaN,2022-09-27 16:00:00,2022-09-27 17:00:00
67890,BZN|FI,27.09.2022 17:00 - 27.09.2022 18:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 17:00 - 27.09.2022 18:00,8468,NaN,27.09.2022 17:00 - 27.09.2022 18:00,NaN,NaN,2022-09-27 17:00:00,2022-09-27 18:00:00
67891,BZN|FI,27.09.2022 18:00 - 27.09.2022 19:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 18:00 - 27.09.2022 19:00,8666,NaN,27.09.2022 18:00 - 27.09.2022 19:00,NaN,NaN,2022-09-27 18:00:00,2022-09-27 19:00:00
67892,BZN|FI,27.09.2022 19:00 - 27.09.2022 20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 19:00 - 27.09.2022 20:00,8673,NaN,27.09.2022 19:00 - 27.09.2022 20:00,NaN,NaN,2022-09-27 19:00:00,2022-09-27 20:00:00
67893,BZN|FI,27.09.2022 20:00 - 27.09.2022 21:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 20:00 - 27.09.2022 21:00,8351,NaN,27.09.2022 20:00 - 27.09.2022 21:00,NaN,NaN,2022-09-27 20:00:00,2022-09-27 21:00:00
67894,BZN|FI,27.09.2022 21:00 - 27.09.2022 22:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 21:00 - 27.09.2022 22:00,8217,NaN,27.09.2022 21:00 - 27.09.2022 22:00,NaN,NaN,2022-09-27 21:00:00,2022-09-27 22:00:00
67895,BZN|FI,27.09.2022 22:00 - 27.09.2022 23:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 22:00 - 27.09.2022 23:00,7990,NaN,27.09.2022 22:00 - 27.09.2022 23:00,NaN,NaN,2022-09-27 22:00:00,2022-09-27 23:00:00
67896,BZN|FI,27.09.2022 23:00 - 28.09.2022 00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.09.2022 23:00 - 28.09.2022 00:00,7635,NaN,27.09.2022 23:00 - 28.09.2022 00:00,NaN,NaN,2022-09-27 23:00:00,2022-09-28 00:00:00
67897,BZN|FI,28.09.2022 00:00 - 28.09.2022 01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 00:00 - 28.09.2022 01:00,7395,NaN,28.09.2022 00:00 - 28.09.2022 01:00,NaN,NaN,2022-09-28 00:00:00,2022-09-28 01:00:00
67898,BZN|FI,28.09.2022 01:00 - 28.09.2022 02:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 01:00 - 28.09.2022 02:00,7297,NaN,28.09.2022 01:00 - 28.09.2022 02:00,NaN,NaN,2022-09-28 01:00:00,2022-09-28 02:00:00
67899,BZN|FI,28.09.2022 02:00 - 28.09.2022 03:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 02:00 - 28.09.2022 03:00,7271,NaN,28.09.2022 02:00 - 28.09.2022 03:00,NaN,NaN,2022-09-28 02:00:00,2022-09-28 03:00:00
67900,BZN|FI,28.09.2022 03:00 - 28.09.2022 04:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 03:00 - 28.09.2022 04:00,7304,NaN,28.09.2022 03:00 - 28.09.2022 04:00,NaN,NaN,2022-09-28 03:00:00,2022-09-28 04:00:00
67901,BZN|FI,28.09.2022 04:00 - 28.09.2022 05:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 04:00 - 28.09.2022 05:00,7505,NaN,28.09.2022 04:00 - 28.09.2022 05:00,NaN,NaN,2022-09-28 04:00:00,2022-09-28 05:00:00
67902,BZN|FI,28.09.2022 05:00 - 28.09.2022 06:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 05:00 - 28.09.2022 06:00,8177,NaN,28.09.2022 05:00 - 28.09.2022 06:00,NaN,NaN,2022-09-28 05:00:00,2022-09-28 06:00:00
67903,BZN|FI,28.09.2022 06:00 - 28.09.2022 07:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 06:00 - 28.09.2022 07:00,8436,NaN,28.09.2022 06:00 - 28.09.2022 07:00,NaN,NaN,2022-09-28 06:00:00,2022-09-28 07:00:00
67904,BZN|FI,28.09.2022 07:00 - 28.09.2022 08:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 07:00 - 28.09.2022 08:00,8628,NaN,28.09.2022 07:00 - 28.09.2022 08:00,NaN,NaN,2022-09-28 07:00:00,2022-09-28 08:00:00
67905,BZN|FI,28.09.2022 08:00 - 28.09.2022 09:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 08:00 - 28.09.2022 09:00,8726,NaN,28.09.2022 08:00 - 28.09.2022 09:00,NaN,NaN,2022-09-28 08:00:00,2022-09-28 09:00:00
67906,BZN|FI,28.09.2022 09:00 - 28.09.2022 10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 09:00 - 28.09.2022 10:00,8709,NaN,28.09.2022 09:00 - 28.09.2022 10:00,NaN,NaN,2022-09-28 09:00:00,2022-09-28 10:00:00
67907,BZN|FI,28.09.2022 10:00 - 28.09.2022 11:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 10:00 - 28.09.2022 11:00,8747,NaN,28.09.2022 10:00 - 28.09.2022 11:00,NaN,NaN,2022-09-28 10:00:00,2022-09-28 11:00:00
67908,BZN|FI,28.09.2022 11:00 - 28.09.2022 12:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 11:00 - 28.09.2022 12:00,8690,NaN,28.09.2022 11:00 - 28.09.2022 12:00,NaN,NaN,2022-09-28 11:00:00,2022-09-28 12:00:00
67909,BZN|FI,28.09.2022 12:00 - 28.09.2022 13:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 12:00 - 28.09.2022 13:00,8674,NaN,28.09.2022 12:00 - 28.09.2022 13:00,NaN,NaN,2022-09-28 12:00:00,2022-09-28 13:00:00
67910,BZN|FI,28.09.2022 13:00 - 28.09.2022 14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 13:00 - 28.09.2022 14:00,8638,NaN,28.09.2022 13:00 - 28.09.2022 14:00,NaN,NaN,2022-09-28 13:00:00,2022-09-28 14:00:00
67911,BZN|FI,28.09.2022 14:00 - 28.09.2022 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 14:00 - 28.09.2022 15:00,8581,NaN,28.09.2022 14:00 - 28.09.2022 15:00,NaN,NaN,2022-09-28 14:00:00,2022-09-28 15:00:00
67912,BZN|FI,28.09.2022 15:00 - 28.09.2022 16:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,28.09.2022 15:00 - 28.09.2022 16:00,8544,NaN,28.09.2022 15:00 - 28.09.2022 16:00,NaN,NaN,2022-09-28 15:00:00,2022-09-28 16:00:00

The data has been acquired 26.9. --> drop all rows with date larger than this as they contain only NaN values

In [55]:
df = df[df.start_time < pd.Timestamp('2022-09-26T15')]

In [56]:
df

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],Hydro Run-of-river and poundage - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],...,Waste - Actual Aggregated [MW],Wind Onshore - Actual Aggregated [MW],Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,start_time,end_time
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,861.0,655.0,1.0,396.0,735.0,2774.0,208.0,...,55.0,214.0,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,2015-01-01 00:00:00,2015-01-01 01:00:00
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,858.0,646.0,1.0,397.0,668.0,2773.0,208.0,...,49.0,208.0,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,2015-01-01 01:00:00,2015-01-01 02:00:00
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,843.0,648.0,1.0,396.0,669.0,2773.0,208.0,...,47.0,250.0,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,2015-01-01 02:00:00,2015-01-01 03:00:00
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,733.0,646.0,1.0,396.0,605.0,2773.0,208.0,...,47.0,264.0,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,2015-01-01 03:00:00,2015-01-01 04:00:00
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,734.0,646.0,1.0,399.0,594.0,2773.0,208.0,...,45.0,274.0,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,2015-01-01 04:00:00,2015-01-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67859,BZN|FI,26.09.2022 10:00 - 26.09.2022 11:00,808,150,331,2,235,1334,3728,51,...,23,639,26.09.2022 10:00 - 26.09.2022 11:00,8599,8809,26.09.2022 10:00 - 26.09.2022 11:00,284.65,EUR,2022-09-26 10:00:00,2022-09-26 11:00:00
67860,BZN|FI,26.09.2022 11:00 - 26.09.2022 12:00,808,159,345,2,225,1261,3728,49,...,23,676,26.09.2022 11:00 - 26.09.2022 12:00,8538,8787,26.09.2022 11:00 - 26.09.2022 12:00,272.90,EUR,2022-09-26 11:00:00,2022-09-26 12:00:00
67861,BZN|FI,26.09.2022 12:00 - 26.09.2022 13:00,802,175,331,0,223,1078,3726,52,...,24,700,26.09.2022 12:00 - 26.09.2022 13:00,8465,8713,26.09.2022 12:00 - 26.09.2022 13:00,275.75,EUR,2022-09-26 12:00:00,2022-09-26 13:00:00
67862,BZN|FI,26.09.2022 13:00 - 26.09.2022 14:00,811,161,322,0,225,1033,3728,59,...,23,726,26.09.2022 13:00 - 26.09.2022 14:00,8428,8634,26.09.2022 13:00 - 26.09.2022 14:00,283.92,EUR,2022-09-26 13:00:00,2022-09-26 14:00:00
67863,BZN|FI,26.09.2022 14:00 - 26.09.2022 15:00,810,142,318,1,222,962,3726,55,...,23,711,26.09.2022 14:00 - 26.09.2022 15:00,8375,8562,26.09.2022 14:00 - 26.09.2022 15:00,283.97,EUR,2022-09-26 14:00:00,2022-09-26 15:00:00

## Create a variable for the day only

In [57]:
df['start_time_day'] = df['start_time'].dt.date

/tmp/ipykernel_14543/1683599061.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start_time_day'] = df['start_time'].dt.date

## Change datatypes

In [58]:
df.dtypes

Area                                                                 object
MTU                                                                  object
Biomass  - Actual Aggregated [MW]                                    object
Fossil Gas  - Actual Aggregated [MW]                                 object
Fossil Hard coal  - Actual Aggregated [MW]                           object
Fossil Oil  - Actual Aggregated [MW]                                 object
Fossil Peat  - Actual Aggregated [MW]                                object
Hydro Run-of-river and poundage  - Actual Aggregated [MW]            object
Nuclear  - Actual Aggregated [MW]                                    object
Other  - Actual Aggregated [MW]                                      object
Other renewable  - Actual Aggregated [MW]                            object
Waste  - Actual Aggregated [MW]                                      object
Wind Onshore  - Actual Aggregated [MW]                               object
Time (CET/CEST)                                                      object
Day-ahead Total Load Forecast [MW] - BZN|FI                          object
Actual Total Load [MW] - BZN|FI                                      object
MTU (CET/CEST)                                                       object
Day-ahead Price [EUR/MWh]                                            object
Currency                                                             object
start_time                                                   datetime64[ns]
end_time                                                     datetime64[ns]
start_time_day                                                       object
dtype: object

In [59]:
df['Actual Total Load [MW] - BZN|FI'] = pd.to_numeric(df['Actual Total Load [MW] - BZN|FI'])

/tmp/ipykernel_14543/2637970014.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Actual Total Load [MW] - BZN|FI'] = pd.to_numeric(df['Actual Total Load [MW] - BZN|FI'])

In [60]:
df['Day-ahead Price [EUR/MWh]'] = pd.to_numeric(df['Day-ahead Price [EUR/MWh]'])

/tmp/ipykernel_14543/2391199815.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day-ahead Price [EUR/MWh]'] = pd.to_numeric(df['Day-ahead Price [EUR/MWh]'])

In [61]:
df['Fossil Oil  - Actual Aggregated [MW]'] = pd.to_numeric(df['Fossil Oil  - Actual Aggregated [MW]'])

/tmp/ipykernel_14543/4030027584.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Fossil Oil  - Actual Aggregated [MW]'] = pd.to_numeric(df['Fossil Oil  - Actual Aggregated [MW]'])

In [62]:
df.columns

Index(['Area', 'MTU', 'Biomass  - Actual Aggregated [MW]',
       'Fossil Gas  - Actual Aggregated [MW]',
       'Fossil Hard coal  - Actual Aggregated [MW]',
       'Fossil Oil  - Actual Aggregated [MW]',
       'Fossil Peat  - Actual Aggregated [MW]',
       'Hydro Run-of-river and poundage  - Actual Aggregated [MW]',
       'Nuclear  - Actual Aggregated [MW]', 'Other  - Actual Aggregated [MW]',
       'Other renewable  - Actual Aggregated [MW]',
       'Waste  - Actual Aggregated [MW]',
       'Wind Onshore  - Actual Aggregated [MW]', 'Time (CET/CEST)',
       'Day-ahead Total Load Forecast [MW] - BZN|FI',
       'Actual Total Load [MW] - BZN|FI', 'MTU (CET/CEST)',
       'Day-ahead Price [EUR/MWh]', 'Currency', 'start_time', 'end_time',
       'start_time_day'],
      dtype='object')

## Change all columns with numerical information to numeric and calculate total generation

In [63]:
gen_columns = list(generation.columns)

In [64]:
data = df[df.columns.intersection(gen_columns)]

In [65]:
data.drop(columns = ['MTU', 'Area'], inplace = True)

/tmp/ipykernel_14543/322307718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(columns = ['MTU', 'Area'], inplace = True)

In [66]:
for column in data.columns:
    data[column] = pd.to_numeric(data[column])

/tmp/ipykernel_14543/2266917257.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[column] = pd.to_numeric(data[column])

In [67]:
df['generation_total'] = data.sum(axis = 1)

/tmp/ipykernel_14543/1472409844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['generation_total'] = data.sum(axis = 1)

In [68]:
for column in data.columns:
    df[column] = pd.to_numeric(df[column])

/tmp/ipykernel_14543/2217477038.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = pd.to_numeric(df[column])

In [69]:
df['Day-ahead Total Load Forecast [MW] - BZN|FI'] = pd.to_numeric(df['Day-ahead Total Load Forecast [MW] - BZN|FI'])

/tmp/ipykernel_14543/1856165041.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Day-ahead Total Load Forecast [MW] - BZN|FI'] = pd.to_numeric(df['Day-ahead Total Load Forecast [MW] - BZN|FI'])

In [72]:
df.head()

,Area,MTU,Biomass - Actual Aggregated [MW],Fossil Gas - Actual Aggregated [MW],Fossil Hard coal - Actual Aggregated [MW],Fossil Oil - Actual Aggregated [MW],Fossil Peat - Actual Aggregated [MW],Hydro Run-of-river and poundage - Actual Aggregated [MW],Nuclear - Actual Aggregated [MW],Other - Actual Aggregated [MW],...,Time (CET/CEST),Day-ahead Total Load Forecast [MW] - BZN|FI,Actual Total Load [MW] - BZN|FI,MTU (CET/CEST),Day-ahead Price [EUR/MWh],Currency,start_time,end_time,start_time_day,generation_total
0,BZN|FI,01.01.2015 00:00 - 01.01.2015 01:00,865.0,861.0,655.0,1.0,396.0,735.0,2774.0,208.0,...,01.01.2015 00:00 - 01.01.2015 01:00,9122.0,9229.0,01.01.2015 00:00 - 01.01.2015 01:00,27.38,EUR,2015-01-01 00:00:00,2015-01-01 01:00:00,2015-01-01,6808.0
1,BZN|FI,01.01.2015 01:00 - 01.01.2015 02:00,874.0,858.0,646.0,1.0,397.0,668.0,2773.0,208.0,...,01.01.2015 01:00 - 01.01.2015 02:00,8835.0,8893.0,01.01.2015 01:00 - 01.01.2015 02:00,23.37,EUR,2015-01-01 01:00:00,2015-01-01 02:00:00,2015-01-01,6726.0
2,BZN|FI,01.01.2015 02:00 - 01.01.2015 03:00,880.0,843.0,648.0,1.0,396.0,669.0,2773.0,208.0,...,01.01.2015 02:00 - 01.01.2015 03:00,8668.0,8735.0,01.01.2015 02:00 - 01.01.2015 03:00,19.33,EUR,2015-01-01 02:00:00,2015-01-01 03:00:00,2015-01-01,6759.0
3,BZN|FI,01.01.2015 03:00 - 01.01.2015 04:00,872.0,733.0,646.0,1.0,396.0,605.0,2773.0,208.0,...,01.01.2015 03:00 - 01.01.2015 04:00,8613.0,8626.0,01.01.2015 03:00 - 01.01.2015 04:00,17.66,EUR,2015-01-01 03:00:00,2015-01-01 04:00:00,2015-01-01,6589.0
4,BZN|FI,01.01.2015 04:00 - 01.01.2015 05:00,881.0,734.0,646.0,1.0,399.0,594.0,2773.0,208.0,...,01.01.2015 04:00 - 01.01.2015 05:00,8685.0,8674.0,01.01.2015 04:00 - 01.01.2015 05:00,17.53,EUR,2015-01-01 04:00:00,2015-01-01 05:00:00,2015-01-01,6599.0

In [70]:
df.to_csv('./data/price_load_gen.csv')